org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.configuration-cache=false
org.gradle.configuration-cache.problems=warn
android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=false
kotlin.incremental=false
